In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import io

In [2]:
df=pd.read_csv('Churn_Modelling.csv')

In [3]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
x=df.iloc[:,:-1].values
print(x)
y=df.iloc[:,-1].values
print(y)

[[1 15634602 'Hargrave' ... 1 1 101348.88]
 [2 15647311 'Hill' ... 0 1 112542.58]
 [3 15619304 'Onio' ... 1 0 113931.57]
 ...
 [9998 15584532 'Liu' ... 0 1 42085.58]
 [9999 15682355 'Sabbatini' ... 1 0 92888.52]
 [10000 15628319 'Walker' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]

In [5]:
print(df.isnull().sum())

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
df.duplicated().sum()

0

In [10]:
df.drop(['Surname'],axis=1,inplace=True)
df.drop(['CustomerId','Gender','Geography'],axis=1,inplace=True)

In [12]:
df

,RowNumber,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,619,42,2,0.00,1,1,1,101348.88,1
1,2,608,41,1,83807.86,1,0,1,112542.58,0
2,3,502,42,8,159660.80,3,1,0,113931.57,1
3,4,699,39,1,0.00,2,0,0,93826.63,0
4,5,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...
9995,9996,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,792,28,4,130142.79,1,1,0,38190.78,0

In [11]:
df.describe()

,RowNumber,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [13]:
scaler=MinMaxScaler()
df1=pd.DataFrame(scaler.fit_transform(df))
df1

,0,1,2,3,4,5,6,7,8,9
0,0.0000,0.538,0.324324,0.2,0.000000,0.000000,1.0,1.0,0.506735,1.0
1,0.0001,0.516,0.310811,0.1,0.334031,0.000000,0.0,1.0,0.562709,0.0
2,0.0002,0.304,0.324324,0.8,0.636357,0.666667,1.0,0.0,0.569654,1.0
3,0.0003,0.698,0.283784,0.1,0.000000,0.333333,0.0,0.0,0.469120,0.0
4,0.0004,1.000,0.337838,0.2,0.500246,0.000000,1.0,1.0,0.395400,0.0
...,...,...,...,...,...,...,...,...,...,...
9995,0.9996,0.842,0.283784,0.5,0.000000,0.333333,1.0,0.0,0.481341,0.0
9996,0.9997,0.332,0.229730,1.0,0.228657,0.000000,1.0,1.0,0.508490,0.0
9997,0.9998,0.718,0.243243,0.7,0.000000,0.000000,0.0,1.0,0.210390,1.0
9998,0.9999,0.844,0.324324,0.3,0.299226,0.333333,1.0,0.0,0.464429,1.0
9999,1.0000,0.884,0.135135,0.4,0.518708,0.000000,1.0,0.0,0.190914,0.0

In [14]:
x1=df1.iloc[:,:-1].values
print(x1)
y1=df1.iloc[:,-1].values
print(y1)

[[0.00000000e+00 5.38000000e-01 3.24324324e-01 ... 1.00000000e+00
  1.00000000e+00 5.06734893e-01]
 [1.00010001e-04 5.16000000e-01 3.10810811e-01 ... 0.00000000e+00
  1.00000000e+00 5.62708739e-01]
 [2.00020002e-04 3.04000000e-01 3.24324324e-01 ... 1.00000000e+00
  0.00000000e+00 5.69654352e-01]
 ...
 [9.99799980e-01 7.18000000e-01 2.43243243e-01 ... 0.00000000e+00
  1.00000000e+00 2.10390092e-01]
 [9.99899990e-01 8.44000000e-01 3.24324324e-01 ... 1.00000000e+00
  0.00000000e+00 4.64429053e-01]
 [1.00000000e+00 8.84000000e-01 1.35135135e-01 ... 1.00000000e+00
  0.00000000e+00 1.90914232e-01]]
[1. 0. 1. ... 1. 1. 0.]

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x1,y1,test_size=0.2)

In [16]:
print(x_train)
print(len(x_train))
print(x_test)
print(len(x_test))

[[0.82088209 0.722      0.14864865 ... 1.         0.         0.15901449]
 [0.92339234 0.386      0.17567568 ... 0.         0.         0.30919028]
 [0.98639864 0.814      0.33783784 ... 1.         1.         0.01743091]
 ...
 [0.0370037  0.902      0.32432432 ... 1.         1.         0.05293861]
 [0.96279628 0.582      0.17567568 ... 1.         0.         0.29961066]
 [0.75327533 0.82       0.2027027  ... 0.         1.         0.78331796]]
8000
[[0.06190619 0.646      0.25675676 ... 1.         1.         0.91662359]
 [0.62376238 0.56       0.13513514 ... 1.         1.         0.66634464]
 [0.60546055 0.566      0.39189189 ... 1.         1.         0.03165932]
 ...
 [0.24952495 0.232      0.51351351 ... 1.         0.         0.98820702]
 [0.2570257  0.326      0.17567568 ... 1.         0.         0.42117547]
 [0.02950295 0.846      0.09459459 ... 1.         0.         0.36825917]]
2000